### ISSUE TITLE
[FEATURE] add npmrc file

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#361] opened 2021-06-01 13:55 UTC
We could add npmrc/nvmrc file to the root in order to define node version and maybe some other config options (for instance when you use nvm). That way we can make sure people are using the right node version (for instance the libs won't work with node 16 or something).

https://docs.npmjs.com/cli/v7/configuring-npm/npmrc
https://github.com/nvm-sh/nvm#nvmrc

**Comment by iruzevic** [comment] 2021-06-27 21:50
this is a duplicate of #77 so I will close it

**Closed by iruzevic** 2021-06-27 21:50 UTC
Labels: feature request, research
