### ISSUE TITLE
Woocommerce

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-frontend-libs#684] opened 2022-11-16 14:06 UTC
When I install woocommerce plugin there is error on admin page and i cannot edit pages and posts .... 
When i change to other theme than works normal but when i chnage to eightshift ...... i get woocommerce error

`TypeError: Cannot read properties of undefined (reading 'startsWith')
    at e.getAttributesWithDefaults (http://dev.cop.com/wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/wc-blocks.js?ver=edc8c61c9712604dbdb967565c8043d6:1:5091)
    at e.render (http://dev.cop.com/wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/wc-blocks.js?ver=edc8c61c9712604dbdb967565c8043d6:1:5388)
    at finishClassComponent (http://dev.cop.com/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:17515:33)
    at updateClassComponent (http://dev.cop.com/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:17465:26)
    at beginWork (http://dev.cop.com/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:19103:18)
    at HTMLUnknownElement.callCallback (http://dev.cop.com/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:3942:16)
    at Object.invokeGuardedCallbackDev (http://dev.cop.com/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:3991:18)
    at invokeGuardedCallback (http://dev.cop.com/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:4053:33)
    at beginWork$1 (http://dev.cop.com/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:23994:9)
    at performUnitOfWork (http://dev.cop.com/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:22806:14)`

**Comment by marijang** [comment] 2022-11-17 06:48
To support woocommerce i think it is good time to add that.

For me i create service like woocommerceSupport and add all functions to support and change layout.

Currently in that file i m
Adding all methods to change woocommerce components like paragraph heading and buttons. 

And due this problem i disable wc-blocks.js and it works now.

Also changing woocomerce template files i just copy template files from plugin and changing it inside theme directory so there is no problems with that. When i finish with that maybe we can add this as   First version of woocommerce support.

Also it will be great to separate components and blocks folders somehow that is only for woocommerce like

Src/woocommerce/components
Src/woocommerce/custom
Src/woocommerce/templates

And add support to overide woocommerce looking for template files in src/woocommerce/templates instead of looking inside root of the theme

Now woocommerce wants theme-name/woocommerce path

If you can help with this that will be great:)

For wc-blocks.js i find the same line. I will try to investigate more. Something is wrong obviously:)

**Comment by marijang** [comment] 2022-11-21 16:06
It seems that registration.js registerBlock function doesn't create name inside block only attributes

**Comment by dingo-d** [comment] 2022-11-23 10:23
I haven't checked how WooCommerce is registering their blocks, but what I did with Gravity forms was to unregister their blocks using `unregister_block_type`, and then register them again, but with added attributes that are missing and causing errors.

Then just add the allowed blocks inside the `allowed_block_types_all` callback so that they appear in the appender, and you can use group block if you need a wrapper, and inside just use the woo blocks.

**Comment by dingo-d** [comment] 2022-11-23 11:15
Ok, I can confirm that something is odd when you hover over eightshift blocks, because then I get the error.

I was able to add the woocommerce blocks like this (inside `Blocks.php`):

```php

	// Inside the register method:
	
	// Limits the usage of only custom project blocks.
	\add_filter('allowed_block_types_all', [$this, 'allowOnlyCustomBlocks'], 10, 2);

	public function allowOnlyCustomBlocks($allowedBlockTypes, \WP_Block_Editor_Context $blockEditorContext): array
	{
		// If all blocks are allowed, $allowedBlocks will be === true. If this is the case, we only
		// wish to allow our custom blocks.
		if (!is_array($allowedBlockTypes)) {
			$allowedBlockTypes = array_merge(
				(array)$this->getAllBlocksList([], $blockEditorContext)
			);
		}

		$allowedBlockTypes = $this->unsetBlocks($allowedBlockTypes, $this->blocksDisallowedByDefault());

		// WooCommerce blocks.
		if (class_exists(\WooCommerce::class) && \is_array($allowedBlockTypes)) {
			$allowedBlockTypes[] = 'woocommerce/active-filters';
			$allowedBlockTypes[] = 'woocommerce/all-products';
			$allowedBlockTypes[] = 'woocommerce/all-reviews';
			$allowedBlockTypes[] = 'woocommerce/attribute-filter';
			$allowedBlockTypes[] = 'woocommerce/cart';
			$allowedBlockTypes[] = 'woocommerce/cart-accepted-payment-methods-block';
			$allowedBlockTypes[] = 'woocommerce/cart-express-payment-block';
			$allowedBlockTypes[] = 'woocommerce/cart-items-block';
			$allowedBlockTypes[] = 'woocommerce/cart-line-items-block';
			$allowedBlockTypes[] = 'woocommerce/cart-order-summary-block';
			$allowedBlockTypes[] = 'woocommerce/cart-order-summary-coupon-form-block';
			$allowedBlockTypes[] = 'woocommerce/cart-order-summary-discount-block';
			$allowedBlockTypes[] = 'woocommerce/cart-order-summary-fee-block';
			$allowedBlockTypes[] = 'woocommerce/cart-order-summary-heading-block';
			$allowedBlockTypes[] = 'woocommerce/cart-order-summary-shipping-block';
			$allowedBlockTypes[] = 'woocommerce/cart-order-summary-subtotal-block';
			$allowedBlockTypes[] = 'woocommerce/cart-order-summary-taxes-block';
			$allowedBlockTypes[] = 'woocommerce/cart-totals-block';
			$allowedBlockTypes[] = 'woocommerce/checkout';
			$allowedBlockTypes[] = 'woocommerce/checkout-actions-block';
			$allowedBlockTypes[] = 'woocommerce/checkout-billing-address-block';
			$allowedBlockTypes[] = 'woocommerce/checkout-contact-information-block';
			$allowedBlockTypes[] = 'woocommerce/checkout-express-payment-block';
			$allowedBlockTypes[] = 'woocommerce/checkout-fields-block';
			$allowedBlockTypes[] = 'woocommerce/checkout-order-note-block';
			$allowedBlockTypes[] = 'woocommerce/checkout-order-summary-block';
			$allowedBlockTypes[] = 'woocommerce/checkout-order-summary-cart-items-block';
			$allowedBlockTypes[] = 'woocommerce/checkout-order-summary-coupon-form-block';
			$allowedBlockTypes[] = 'woocommerce/checkout-order-summary-discount-block';
			$allowedBlockTypes[] = 'woocommerce/checkout-order-summary-fee-block';
			$allowedBlockTypes[] = 'woocommerce/checkout-order-summary-shipping-block';
			$allowedBlockTypes[] = 'woocommerce/checkout-order-summary-subtotal-block';
			$allowedBlockTypes[] = 'woocommerce/checkout-order-summary-taxes-block';
			$allowedBlockTypes[] = 'woocommerce/checkout-payment-block';
			$allowedBlockTypes[] = 'woocommerce/checkout-shipping-address-block';
			$allowedBlockTypes[] = 'woocommerce/checkout-shipping-methods-block';
			$allowedBlockTypes[] = 'woocommerce/checkout-terms-block';
			$allowedBlockTypes[] = 'woocommerce/checkout-totals-block';
			$allowedBlockTypes[] = 'woocommerce/empty-cart-block';
			$allowedBlockTypes[] = 'woocommerce/featured-category';
			$allowedBlockTypes[] = 'woocommerce/featured-product';
			$allowedBlockTypes[] = 'woocommerce/filled-cart-block';
			$allowedBlockTypes[] = 'woocommerce/filter-wrapper';
			$allowedBlockTypes[] = 'woocommerce/handpicked-products';
			$allowedBlockTypes[] = 'woocommerce/legacy-template';
			$allowedBlockTypes[] = 'woocommerce/mini-cart';
			$allowedBlockTypes[] = 'woocommerce/mini-cart-contents';
			$allowedBlockTypes[] = 'woocommerce/proceed-to-checkout-block';
			$allowedBlockTypes[] = 'woocommerce/product-add-to-cart';
			$allowedBlockTypes[] = 'woocommerce/product-best-sellers';
			$allowedBlockTypes[] = 'woocommerce/product-button';
			$allowedBlockTypes[] = 'woocommerce/product-categories';
			$allowedBlockTypes[] = 'woocommerce/product-category';
			$allowedBlockTypes[] = 'woocommerce/product-category-list';
			$allowedBlockTypes[] = 'woocommerce/product-image';
			$allowedBlockTypes[] = 'woocommerce/product-new';
			$allowedBlockTypes[] = 'woocommerce/product-on-sale';
			$allowedBlockTypes[] = 'woocommerce/product-price';
			$allowedBlockTypes[] = 'woocommerce/product-query';
			$allowedBlockTypes[] = 'woocommerce/product-rating';
			$allowedBlockTypes[] = 'woocommerce/product-sale-badge';
			$allowedBlockTypes[] = 'woocommerce/product-search';
			$allowedBlockTypes[] = 'woocommerce/product-sku';
			$allowedBlockTypes[] = 'woocommerce/product-stock-indicator';
			$allowedBlockTypes[] = 'woocommerce/product-summary';
			$allowedBlockTypes[] = 'woocommerce/product-tag';
			$allowedBlockTypes[] = 'woocommerce/product-tag-list';
			$allowedBlockTypes[] = 'woocommerce/product-title';
			$allowedBlockTypes[] = 'woocommerce/product-top-rated';
			$allowedBlockTypes[] = 'woocommerce/products-by-attribute';
			$allowedBlockTypes[] = 'woocommerce/rating-filter';
			$allowedBlockTypes[] = 'woocommerce/reviews-by-category';
			$allowedBlockTypes[] = 'woocommerce/reviews-by-product';
			$allowedBlockTypes[] = 'woocommerce/single-product';
			$allowedBlockTypes[] = 'woocommerce/stock-filter';
		}

		return is_array($allowedBlockTypes) ? array_values($allowedBlockTypes) : $allowedBlockTypes;
	}

	/**
	 * Removes blocks from $original array
	 *
	 * @param  array<string>|bool $original Array of blocks.
	 * @param array<bool> $toRemove Array of blocks to remove.
	 *
	 * @return array<string>|bool
	 */
	private function unsetBlocks($original, array $toRemove)
	{
		if (!is_array($original)) {
			return $original;
		}

		return array_values(array_filter($original, function ($blockName) use ($toRemove) {
			return !isset($toRemove[$blockName]);
		}));
	}

	/**
	 * Returns an array of custom blocks that can't be inserted in the editor manually.
	 *
	 * Should be added as `'safer-internet/block-name' => true` inside the array.
	 *
	 * @return array<string, bool>
	 */
	private function blocksDisallowedByDefault(): array
	{
		return [];
	}
```

And they seem to be working fine when I select them

<img width="1834" alt="image" src="https://user-images.githubusercontent.com/8638515/203533287-1b8b88e7-b8cf-47b7-b683-043dc1f18791.png">

But when I hover over our blocks the error you get appears for me as well...

**Comment by dingo-d** [comment] 2023-10-04 16:09
@marijang so adding `name` attribute in your block's `manifest.json` will prevent the error from happening.

I tried adding the name as 

```json
"name": "eightshift-boilerplate/test-block",
```

But that didn't work. Just adding 

```json
"name": "test-block",
```

did. However, when adding this block it's just rendered in the code as

```html
<!-- wp:test-block {"uniqueWrapperId":"w6vd7i2m"} /-->
```

Which works on the initial load, but when saved will throw an error:

> Your site doesn’t include support for the "core/test-block" block. You can leave this block intact or remove it entirely.

I tried adding to my `block.js` file:

```js
	props = {
		...props,
		name: props.attributes.blockFullName
	}
```

But that didn't work. The block is still rendered without the namespace in the editor...

@iruzevic @goranalkovic-infinum Did you try seeing what could be the culprit, or how we could fix this?

This basically makes Eightshift dev kit unusable with WooCommerce...

**Comment by dingo-d** [comment] 2023-10-04 16:35
I submitted the PR for a fix, that apparently fixes this (just adding optional chaining to the JS part in WooCommerce blocks).

I have no idea when/if this ever gets merged or released 🤷🏼‍♂️

**Comment by dingo-d** [comment] 2023-10-20 15:24
@goranalkovic-infinum Would adding a `name` field in the manifest for the blocks fix this issue? The replacing the `blockName` with `name`?

The manifest should be compatible with https://raw.githubusercontent.com/WordPress/gutenberg/trunk/schemas/json/block.json

**Comment by iruzevic** [comment] 2023-10-20 17:04
I will test this on Monday

**Comment by iruzevic** [comment] 2023-10-23 08:17
The PR is created, the issue was introduced by me.

**Closed** 2023-10-23 08:18 UTC

**Comment by iruzevic** [comment] 2023-10-23 08:21
Please update to the latest release https://github.com/infinum/eightshift-frontend-libs/releases/tag/8.6.0

**Comment by dingo-d** [comment] 2023-10-23 11:52
@iruzevic weird, I updated the libs both in the theme, and in my plugin, but am still getting the same error, and when I open the `hooks.js` file, it's not updated 🤷🏼‍♂️

**Comment by iruzevic** [comment] 2023-10-23 12:13
sorry, it is Monday :( Added changes on 8.6.1

**Comment by dingo-d** [comment] 2023-10-23 12:16
No problems, thanks for the quick fix, testing it now 😊

**Comment by dingo-d** [comment] 2023-10-23 12:32
This seems to have fixed the issue with blocks and WooCommerce blocks 🎉 Thanks!
